name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      mongo-db-username: ${{ secrets.MONGO_USERNAME }}
      mongo-db-password: ${{ secrets.MONGO_PASSWORD }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Run tests with coverage
      env:
        QUARKUS_PROFILE: ci
        mongo-db-username: ${{ secrets.MONGO_USERNAME }}
        mongo-db-password: ${{ secrets.MONGO_PASSWORD }}
      run: |
        cd backend
        ./mvnw clean test jacoco:report -Dquarkus.profile=ci -Dquarkus.test.profile.tags=ci
    
    - name: Deploy coverage to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./backend/target/site/jacoco
        destination_dir: coverage